# Generated by Django 5.2.8 on 2025-12-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_options_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='Category of the blog post', max_length=100),
        ),
    ]
