# Generated by Django 5.2.8 on 2025-12-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for the post', max_length=200),
        ),
    ]
