# Generated by Django 5.2.8 on 2025-12-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for this post', null=True, upload_to='blog_images/'),
        ),
    ]
